### ISSUE TITLE
Oldaltartalom lejjebb van csúszva

### ISSUE THREAD

**Issue by DecentM** [Krishtof/TB#17]
A főoldal kivételével minden oldalon van szünet a menüsor és az oldal háttere között.
Szerintem jobb lenne, ha olyan lenne, mint a főoldalon, hogy egységes legyen.

**Comment by Krishtof** [comment]
kapcsolat aloldal kivételével megcsináltam, ott nem jó, mert akk összeolvad a menü meg a body
