### ISSUE TITLE
Helytelen betűtípus

### ISSUE THREAD

**Issue by DecentM** [Krishtof/TB#4]
A funkcionális tesztelés és felhasználói élmény oldal esetében a menü egy másik betűtípust használ

**Comment by Krishtof** [comment]
én droid sanst látok ott is

**Comment by DecentM** [comment]
Képernyőfotók lent, a konzolban ezt dobja ki:
`A(z) https://www.google.com/fonts#UsePlace:use/Collection:Droid+Sans:400,700 stíluslap nem töltődött be, mert a MIME-típusa „text/html” a „text/css” helyett.`

![firefox_2016-03-24_12-41-01](https://cloud.githubusercontent.com/assets/4973610/14016045/ccb7e93c-f1bd-11e5-8e3a-07031393cebb.png)
![firefox_2016-03-24_12-41-15](https://cloud.githubusercontent.com/assets/4973610/14016046/ccbc991e-f1bd-11e5-92e7-ddb7ef123c43.png)

**Comment by Krishtof** [comment]
ez csak egy warning, ettől még behozza a fontot

**Comment by DecentM** [comment]
Pedig csak azokon az oldalakon mondja, ahol nem jó a menü fontja.
Pedig a forráskódban jól van deklarálva text/css-ként.
