### ISSUE TITLE
Menü linkek html-re mutatnak

### ISSUE THREAD

**Issue by DecentM** [Krishtof/TB#5]
Át kell rakni, hogy php-re mutassanak

**Comment by DecentM** [comment]
Ez nem nagy prió, mert a szerver php-t mutat, ha nincs html, de javítsuk ki mindenestre

**Comment by DecentM** [comment]
Ja, látom, ezek a nyelvi fájlban vannak

**Comment by Krishtof** [comment]
nem, volt ami tényleg nem volt jó, de javítottam
