### ISSUE TITLE
Inkonzisztens menüelemek

### ISSUE THREAD

**Issue by DecentM** [Krishtof/TB#6]
A menü nem egységes.
Például a https://staging.testbirds.hu/funkcionalis.php oldalon az összes menüpont a Rólunk.
Néhányon ott van a blog link, és néhányon pedig a sorrend nem egyezik meg a többivel.
Pár menüelem nem a karika animációt használja, hanem valami más.

**Comment by DecentM** [comment]
Jó lenne, ha egy helyen lenne a menüelem megcsinálva, és aztán az az egy jelenne meg mindenhol, egyszerűbb :)

**Comment by Krishtof** [comment]
igen, így lett volna elegáns :P
